#!/bin/bash

echo "Fazendo deploy $(date '+%d/%m/%Y %H:%M')"

cd dist
cp -Rf .git
git init
git add .
git config user.name "Ricardo Pereira"
git config user.email "contato@ricardopedias.com.br"
git commit -m "Deploy em $(date '+%d/%m/%Y %H:%M')"
git branch -M main
git remote add origin git@github.com:regeneracuidado/regeneracuidado.github.io.git
git push origin main --force
cd ../

