#!/bin/bash

parentDir=$(basename $(pwd))

if [ "$parentDir" == "application" ]; then
    echo "Dentro do docker não é possível fazer o deploy"
    exit 1
fi

echo "Fazendo deploy $(date '+%d/%m/%Y %H:%M')"

./npm run dev

cd dist

pwd

if [ -d ".git" ]; then
    rm -Rf .git
fi

git config --global init.defaultBranch main

git init
git remote add origin git@github.com:regeneracuidado/regeneracuidado.github.io.git
git config user.name "Ricardo Pereira"
git config user.email "contato@ricardopedias.com.br"

git add .
git commit -m "Deploy em $(date '+%d/%m/%Y %H:%M')"
git push origin main --force
cd -
